# Generated by Django 6.0 on 2025-12-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AzureData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('round_count', models.IntegerField()),
                ('slim_count', models.IntegerField()),
                ('round_void_count', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slim_void_count', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enqueued_at', models.DateTimeField()),
                ('azure_device_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'azure_data_test',
                'ordering': ['-enqueued_at'],
            },
        ),
    ]
