# Generated by Django 6.0 on 2026-02-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='azuredata',
            name='raw_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='azuredata',
            name='user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
