# Generated by Django 6.0 on 2026-02-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_azuredata_raw_payload_alter_azuredata_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('azure_device_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='azuredata',
            name='user_id',
        ),
        migrations.AddField(
            model_name='azuredata',
            name='device_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='azuredata',
            table='azure_data',
        ),
    ]
